- hosts: linux
  tasks:
  - name: print file content
    command: cat testfile
    register: filecontent
  - debug: msg="File is Empty"
    when: filecontent.stdout==""
  - debug: msg="File is not empty"
    when: filecontent.stdout!=""

